### ISSUE TITLE
Circular references?

### ISSUE THREAD

**Issue by beppe9000** [Tronald/CoordinateSharp#33]
It's me again, I was trying to serialize a class containing a `Coordinate` member but apparently I can't.

```
      (new System.Web.Script.Serialization.JavaScriptSerializer).Serialize(my_object)
```
I get an exception that states that it can't serialize the `Coordinate` instance because of circular references.

I get errors also with Yaml and Json from the [Persist library](https://www.nuget.org/packages/Persist/) that I am using (it's old tough).

Update: Actually I was able to serialize it with:
```
(new YamlDotNet.Serialization.Serializer).Serialize(myObject)
```

It is the underlying lib that Persist uses for Yaml, but it kind of  defies the purpose of having the Persist library....

Do you recommend some other library to easily store an object to a file and back that works with CoordinateSharp's coordinates class ?

**Comment by Tronald** [comment]
The library wasn't built with serialization in mind. None of them are marked `[serializable]` so I know the .NET default serializer in `System.Runtime.Serialization` won't work either. I don't know about using the XML serializer though. I'll have to research this.

Is the YamlDotNet serializer working ok for you so far with a `Coordinate` object though? I'm interested as to why one works, but the other doesn't myself. If it's working to your needs let me know for reference.

**Comment by beppe9000** [comment]
YamlDotNet's deserialization fails "because a parameterless constructor is needed".

Other than that it serializes good:
```
&o0
Latitude:
  Parent: *o0
  DecimalDegree: 41.123456789000002
  DecimalMinute: 7.4074073399999998
  Degrees: 41
  Minutes: 7
  Seconds: 24.444440400000001
  Display: N 41º 7' 24,444"
Longitude:
  Parent: *o0
  DecimalDegree: 12.123456789000001
  DecimalMinute: 7.4074073399999998
  Degrees: 12
  Minutes: 7
  Seconds: 24.444440400000001
  Display: E 12º 7' 24,444"
  Position: E
GeoDate: 1900-01-01T00:00:00.0000000Z
UTM:
  LatZone: T
  LongZone: 33
  Easting: 258516.39999999999
  Northing: 4556450.7000000002
  Equatorial_Radius: 6378137
  Inverse_Flattening: 298.25722356300003
MGRS:
  LatZone: T
  LongZone: 33
  Easting: 58516
  Northing: 56450
  Digraph: TF
Cartesian:
  X: 0.73649373448169964
  Y: 0.15820598029869862
  Z: 0.65768369819156047
CelestialInfo:
  MoonSet: 1900-01-01T15:58:19.7070000Z
  MoonRise: 1900-01-01T06:08:56.7360000Z
  MoonDistance: 373729.95336897188
  MoonIllum:
    Fraction: 0.0080200367783918036
    Angle: 1.7103206536387041
    Phase: 0.97145562544067432
    PhaseName: New Moon
  AdditionalSolarTimes:
    CivilDawn: 1900-01-01T00:00:00.0000000Z
    CivilDusk: 1900-01-01T00:00:00.0000000Z
    NauticalDawn: 1900-01-01T00:00:00.0000000Z
    NauticalDusk: 1900-01-01T00:00:00.0000000Z
  AstrologicalSigns:
    MoonName: ''
    MoonSign: Capricorn
    ZodiacSign: Capricorn
  SolarEclipse:
    LastEclipse:
      HasEclipseData: true
      Date: 1898-01-22T00:00:00.0000000
      PartialEclispeBegin: 1898-01-22T06:34:00.0000000
      MaximumEclipse: 1898-01-22T06:34:00.0000000
      PartialEclispeEnd: 1898-01-22T07:16:17.0000000
    NextEclipse:
      HasEclipseData: true
      Date: 1900-05-28T00:00:00.0000000
      PartialEclispeBegin: 1900-05-28T15:09:54.0000000
      MaximumEclipse: 1900-05-28T16:16:04.0000000
      PartialEclispeEnd: 1900-05-28T17:15:59.0000000
  LunarEclipse:
    LastEclipse:
      HasEclipseData: true
      Date: 1899-12-16T00:00:00.0000000
      Type: Partial
      PenumbralEclipseBegin: 1899-12-16T22:34:00.0000000
      PartialEclispeBegin: 1899-12-16T23:45:00.0000000
      MidEclipse: 1899-12-16T01:26:00.0000000
      PartialEclispeEnd: 1899-12-16T03:07:00.0000000
      PenumbralEclispeEnd: 1899-12-16T04:18:00.0000000
    NextEclipse:
      HasEclipseData: true
      Date: 1900-06-13T00:00:00.0000000
      PenumbralEclipseBegin: 1900-06-13T01:17:00.0000000
      MidEclipse: 1900-06-13T03:28:00.0000000
      PenumbralEclispeEnd: 1900-06-13T05:39:00.0000000
  MoonPhase: 0.97145562544067432
FormatOptions:
  Format: Degree_Minutes_Seconds
  Round: 3
  Display_Symbols: true
  Display_Degree_Symbol: true
  Display_Minute_Symbol: true
  Display_Seconds_Symbol: true
  Position_First: true
EagerLoadSettings:
  Celestial: true
  UTM_MGRS: true
  Cartesian: true
Display: N 41º 7' 24,444" E 12º 7' 24,444"
```

I think I will create my own simplified class for storing coordinates like this JSON: 
`{"lat":"41.123456789", "lon":"12.123456789"}`
And a Read Only Property to convert it to a `CoordinateSharp.Coordinate`.
